version: "3.4"

services:
  mongodb:
    image: mongo:5.0.2
    volumes:
      - mongodata:/data/db
      - mongo-config:/data/configdb
      - ./assets:/assets # directory with asset files, to be imported to MongoDB with mongoimport command
    ports:
      - "27017:27017"

  metabase:
    image: metabase/metabase
    volumes:
      - ./metabase-data:/metabase-data
    ports:
      - "3000:3000"

volumes:
  mongodata:
  mongo-config:
